name: Development

on:
  push:
    branches: [main]

jobs:
  bulid:
    name: Development

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.0]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Node Modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy build files to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: '.next'
          target: '/home/ubuntu/Dominus-frontend/'

      - name: Run SSH command on target
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            PATH=$PATH:/home/ubuntu/.nvm/versions/node/v14.15.0/bin
            pm2 restart dominus-frontend-pm2

      - name: Discord Notify
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Github succeeded.
          webhookUrl: ${{ secrets.WEBHOOK_ID }}
      - name: Discord Notify
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: warn
          details: Github warning.
          webhookUrl: ${{ secrets.WEBHOOK_ID }}
      - name: Discord Notify
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: error
          details: Github error.
          webhookUrl: ${{ secrets.WEBHOOK_ID }}
